# Generated by Django 4.0.3 on 2022-03-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='carsbase.brands', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color', to='carsbase.colors', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model', to='carsbase.models', verbose_name='Модель'),
        ),
    ]
